spring.application.name=DIMS_PROJECT_2

spring.datasource.url=jdbc:mysql://localhost:3306/dims_project_2_db
spring.datasource.username=root
spring.datasource.password=671K#bt!

spring.jpa.hibernate.ddl-auto=update